### ISSUE TITLE
Correct output in MultiModuleBuilds

### ISSUE THREAD

**Issue by arburk** [baloise-incubator/codeql2sonar-maven-plugin#7]
Sonar does not match reported files in multi-module-builds as codeQL prefexis the path with the module's name, e.g. ```Module/src/main/java/...``` instead of ```src/main/java/...```. So the output result needs to be adjusted to enable sonar to match the files.

**Comment by Simran-Gupta234** [comment]
Hi, I would like to work on this issue, can you suggest to me ways to get started?

**Comment by arburk** [comment]
Hi Simran-Gupta234

I already started with it but support and inputs are always welcome. I'm still thinking about how to determine if the path needs adjustment or not. Introducing new flag would be the easiest way. But auto detection is more attractive. What would you suggest?

**Comment by Simran-Gupta234** [comment]
ok, Thank you. I will look at the feature branch.

**Comment by arburk** [comment]
I drafted a quick fix, but would be happier to check cicrumstances (i.e. deviation of standard maven structure, multi module build etc.).

**Comment by Simran-Gupta234** [comment]
yaa, sure I would be much more happier.

**Comment by arburk** [comment]
Approach works in principle nevertheless it can be improved e.g. by retrieving correct source path (and test source path) from pom file. Added corresponding comment/TODO in the code. I'll merge the created feature branch, but leave the issue open for improvements.

**Comment by arburk** [comment]
Issue was resolve by mentioned commits and successfully tested.
